name: .NET

on:
  push:
    branches: [ "*" ]  # Aciona em todas as branches
  pull_request:
    branches: [ "*" ]  # Aciona em todas as branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        cd Loja
        dotnet restore
    - name: Build
      run: |
        cd Loja
        dotnet build --no-restore
    - name: Test
      run: |
        cd Loja
        dotnet test --no-build --verbosity normal